jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-20.04'}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
    - bash: |
        set -o errexit
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m amplpy.modules install gurobi
      displayName: Install dependencies
    - bash: |
        python -m pip install .
      displayName: Install amplpyfinance
    - bash: |
        python -m amplpyfinance.tests
      displayName: Test
