jobs:
- job: test
  pool: {vmImage: 'ubuntu-latest'}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
    - bash: python --version
      displayName: Check python version
    - bash: |
        set -o errexit
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m amplpy.modules install gurobi
      displayName: Install dependencies
    - bash: |
        python -m pip install .
      displayName: Install amplpyfinance
    - bash: |
        python -m amplpyfinance.tests
      displayName: Test
