jobs:
- job: Test
  pool: {vmImage: 'ubuntu-latest'}
  strategy:
    matrix:
      Python 3.10:
        PYTHON_VERSION: 3.10
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - bash: python --version
      displayName: Check python version
    - bash: |
        set -o errexit
        python -m pip install -r requirements.txt
        python -m pip install -r requirements-dev.txt
        python -m amplpy.modules install gurobi
      displayName: Install dependencies
    - bash: |
        python -m pip install .
      displayName: Install amplpyfinance
    - bash: |
        python -m amplpyfinance.tests
      displayName: Test
