name: Test package
run-name: ${{ github.actor }} is building "${{ github.ref_name }}"
on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
          python -m amplpy.modules install gurobi
      - name: Install amplpyfinance
        run: |
          python -m pip install .
      - name: Test
        run: |
          python -m amplpyfinance.tests
